import create from "zustand";

const useStore = create((set) => {
  return {};
});

export function updateStoreStateFromController(pageName, newState) {
  useStore.setState({ [pageName]: newState });
}

const desktopModeProps = {
  ...{
  "Home": {
    "Navbar": {
      "styles": {
        "display": "flex",
        "flexDirection": "row",
        "alignItems": "stretch",
        "justifyContent": "space-between",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "",
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "15px",
        "paddingBottom": "15px",
        "paddingRight": "40px",
        "paddingLeft": "40px",
        "width": "100%",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": null,
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      }
    },
    "NavbarLeft": {
      "styles": {
        "display": "flex",
        "flexDirection": "row",
        "alignItems": "center",
        "justifyContent": "flex-start",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "10px",
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      }
    },
    "NavbarCenter": {
      "styles": {
        "display": "flex",
        "flexDirection": "row",
        "alignItems": "center",
        "justifyContent": "center",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "40px",
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      }
    },
    "NavbarRight": {
      "styles": {
        "display": "flex",
        "flexDirection": "row",
        "alignItems": "center",
        "justifyContent": "flex-end",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "20px",
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      }
    },
    "Image1": {
      "onClick": false,
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "alt": "No preview available",
        "src": "/app-assets/logo.svg"
      }
    },
    "TextBox1": {
      "styles": {
        "alignSelf": "center",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "text": "Atri Labs"
      }
    },
    "Image2": {
      "onClick": false,
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "alt": "No preview available",
        "src": "/app-assets/slack.svg"
      }
    },
    "Image3": {
      "onClick": false,
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "alt": "No preview available",
        "src": "/app-assets/github%20logo.svg"
      }
    },
    "Image4": {
      "onClick": false,
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "alt": "No preview available",
        "src": "/app-assets/Account%20circle.svg"
      }
    },
    "TextBox2": {
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "#1E40AF",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "text": "Gallery"
      }
    },
    "TextBox3": {
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "text": "Docs"
      }
    },
    "Flex5": {
      "styles": {
        "display": "flex",
        "flexDirection": "column",
        "alignItems": "center",
        "justifyContent": "center",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "10px",
        "columnGap": "",
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      }
    },
    "TextBox4": {
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "2rem",
        "textAlign": "left",
        "color": "#1E40AF",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "text": "built using Atri framework"
      }
    },
    "TextBox5": {
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "2rem",
        "textAlign": "left",
        "color": "#1E40AF",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "text": "Explore the apps"
      }
    },
    "Flex6": {
      "styles": {
        "display": "inline-flex",
        "flexDirection": "row",
        "alignItems": "center",
        "justifyContent": "center",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "10px",
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "10px",
        "paddingBottom": "10px",
        "paddingRight": "30px",
        "paddingLeft": "30px",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "40px",
        "borderWidth": "",
        "borderStyle": "solid",
        "borderColor": "#FDA4AF",
        "backgroundImage": "",
        "backgroundColor": "#ffffff",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      }
    },
    "Image5": {
      "onClick": false,
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "alt": "No preview available",
        "src": "/app-assets/search_atri_gallery.svg"
      }
    },
    "Input1": {
      "onChange": false,
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "4px",
        "paddingBottom": "4px",
        "paddingRight": "11px",
        "paddingLeft": "11px",
        "width": "20rem",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "14px",
        "textAlign": "center",
        "color": "",
        "opacity": "1",
        "borderRadius": "2px",
        "borderWidth": "1px",
        "borderStyle": "none",
        "borderColor": "#d9d9d9",
        "backgroundImage": "none",
        "backgroundColor": "#fff",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "value": "",
        "placeholder": "Search Computer Vision apps"
      }
    },
    "Flex7": {
      "styles": {
        "display": "flex",
        "flexDirection": "column",
        "alignItems": "center",
        "justifyContent": "flex-start",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "30px",
        "columnGap": "",
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "60px",
        "marginBottom": "",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "80px",
        "paddingBottom": "80px",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "url(\"/app-assets/gallery_background.png\")",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      }
    },
    "Flex8": {
      "styles": {
        "display": "flex",
        "flexDirection": "row",
        "alignItems": "center",
        "justifyContent": "space-between",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "",
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "20px",
        "paddingBottom": "20px",
        "paddingRight": "40px",
        "paddingLeft": "40px",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      }
    },
    "Dropdown1": {
      "onChange": false,
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "4px",
        "paddingBottom": "4px",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "12px",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "1px",
        "borderStyle": "solid",
        "borderColor": "#D1D5DB",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "values": [
          "Featured"
        ],
        "selectedValue": "",
        "displayedValues": [],
        "disabled": false
      }
    },
    "Button1": {
      "onClick": false,
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "4px",
        "paddingBottom": "4px",
        "paddingRight": "15px",
        "paddingLeft": "15px",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "12px",
        "textAlign": "center",
        "color": "#fff",
        "opacity": "1",
        "borderRadius": "2px",
        "borderWidth": "1px",
        "borderStyle": "solid",
        "borderColor": "#1890ff",
        "backgroundImage": "",
        "backgroundColor": "#1c3fb4",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "text": "Share my work"
      }
    },
    "Flex9": {
      "styles": {
        "display": "flex",
        "flexDirection": "column",
        "alignItems": "center",
        "justifyContent": "center",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "20px",
        "columnGap": "",
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      }
    },
    "TextBox6": {
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "text": "Atri gallery will be live soon!"
      }
    },
    "NavbarWrapper": {
      "styles": {
        "display": "flex",
        "flexDirection": "row",
        "alignItems": "stretch",
        "justifyContent": "flex-start",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "",
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "100%",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "fixed",
        "float": "none",
        "clear": "none",
        "top": 0,
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      }
    },
    "TextBox10": {
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "text": "Get in touch with our Slack community"
      }
    },
    "Image15": {
      "onClick": false,
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "32px",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "fixed",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": 20,
        "right": 20,
        "zIndex": ""
      },
      "custom": {
        "alt": "No preview available",
        "src": "/app-assets/made-with-atri.svg"
      }
    }
  },
  "login": {
    "Image6": {
      "onClick": false,
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "alt": "No preview available",
        "src": "/app-assets/Account%20circle.svg"
      }
    },
    "Image7": {
      "onClick": false,
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "alt": "No preview available",
        "src": "/app-assets/github%20logo.svg"
      }
    },
    "Image8": {
      "onClick": false,
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "alt": "No preview available",
        "src": "/app-assets/slack.svg"
      }
    },
    "TextBox7": {
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "text": "Docs"
      }
    },
    "TextBox8": {
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "#1E40AF",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "text": "Gallery"
      }
    },
    "TextBox9": {
      "styles": {
        "alignSelf": "center",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "text": "Atri Labs"
      }
    },
    "Image9": {
      "onClick": false,
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "alt": "No preview available",
        "src": "/app-assets/logo.svg"
      }
    },
    "Flex18": {
      "styles": {
        "display": "flex",
        "flexDirection": "row",
        "alignItems": "stretch",
        "justifyContent": "flex-start",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "",
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      }
    },
    "Image11": {
      "onClick": false,
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "alt": "No preview available",
        "src": "/app-assets/Account%20circle.svg"
      }
    },
    "Image12": {
      "onClick": false,
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "alt": "No preview available",
        "src": "/app-assets/github%20logo.svg"
      }
    },
    "Image13": {
      "onClick": false,
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "alt": "No preview available",
        "src": "/app-assets/slack.svg"
      }
    },
    "TextBox12": {
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "text": "Docs"
      }
    },
    "TextBox13": {
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "#1E40AF",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "text": "Gallery"
      }
    },
    "TextBox14": {
      "styles": {
        "alignSelf": "center",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "text": "Atri Labs"
      }
    },
    "Image14": {
      "onClick": false,
      "styles": {
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      },
      "custom": {
        "alt": "No preview available",
        "src": "/app-assets/logo.svg"
      }
    },
    "Flex20": {
      "styles": {
        "display": "flex",
        "flexDirection": "row",
        "alignItems": "center",
        "justifyContent": "flex-end",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "20px",
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      }
    },
    "Flex21": {
      "styles": {
        "display": "flex",
        "flexDirection": "row",
        "alignItems": "center",
        "justifyContent": "center",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "40px",
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      }
    },
    "Flex22": {
      "styles": {
        "display": "flex",
        "flexDirection": "row",
        "alignItems": "center",
        "justifyContent": "flex-start",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "10px",
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "0",
        "paddingBottom": "0",
        "paddingRight": "0",
        "paddingLeft": "0",
        "width": "",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      }
    },
    "Flex23": {
      "styles": {
        "display": "flex",
        "flexDirection": "row",
        "alignItems": "stretch",
        "justifyContent": "space-between",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "",
        "alignSelf": "auto",
        "flexGrow": "0",
        "flexShrink": "1",
        "order": "0",
        "marginTop": "0",
        "marginBottom": "0",
        "marginRight": "0",
        "marginLeft": "0",
        "paddingTop": "15px",
        "paddingBottom": "15px",
        "paddingRight": "40px",
        "paddingLeft": "40px",
        "width": "100%",
        "height": "",
        "minWidth": "0",
        "minHeight": "0",
        "maxWidth": "",
        "maxHeight": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "1",
        "borderRadius": "0",
        "borderWidth": "",
        "borderStyle": "none",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": null,
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": ""
      }
    }
  }
}};

const breakpointProps = {
  ...{
  "Home": {
    "478": {
      "NavbarCenter": {
        "styles": {
          "columnGap": "20px"
        }
      },
      "Input1": {
        "styles": {
          "width": "15rem"
        }
      },
      "Flex8": {
        "styles": {
          "paddingLeft": "10px",
          "paddingRight": "10px"
        }
      }
    },
    "991": {
      "Navbar": {
        "styles": {
          "paddingLeft": "20px",
          "paddingRight": "20px"
        }
      }
    }
  },
  "login": {
    "478": {
      "Flex21": {
        "styles": {
          "columnGap": "20px"
        }
      }
    },
    "991": {
      "Flex23": {
        "styles": {
          "paddingLeft": "20px",
          "paddingRight": "20px"
        }
      }
    }
  }
}};

function getViewportDimension() {
  const width = Math.max(
    document.documentElement.clientWidth || 0,
    window.innerWidth || 0
  );
  const height = Math.max(
    document.documentElement.clientHeight || 0,
    window.innerHeight || 0
  );
  return { width, height };
}

function getEffectiveBreakpointWidths(pageName, windowWidth) {
  if (breakpointProps[pageName] === undefined) {
    return [];
  }
  const widths = Object.keys(breakpointProps[pageName]);
  return widths
    .filter((curr) => {
      return parseInt(curr) >= windowWidth;
    })
    .sort((a, b) => {
      return parseInt(a) - parseInt(b);
    });
}

/**
 *
 * effective props is combination of
 */
function getEffectivePropsForPage(pageName) {
  const { width } = getViewportDimension();
  // effectiveProps initially has local changes
  let effectiveProps = JSON.parse(
    JSON.stringify(useStore.getState()[pageName])
  );
  const effectiveWidths = getEffectiveBreakpointWidths(pageName, width);
  effectiveWidths.forEach((effectiveWidth) => {
    const compAliases = Object.keys(breakpointProps[pageName][effectiveWidth]);
    compAliases.forEach((compAlias) => {
      const propNames = Object.keys(
        breakpointProps[pageName][effectiveWidth][compAlias]
      );
      propNames.forEach((propName) => {
        effectiveProps[compAlias][propName] = {
          ...useStore.getState()[pageName][compAlias][propName],
          ...breakpointProps[pageName][effectiveWidth][compAlias][propName],
        };
      });
    });
  });
  return effectiveProps;
}

export function setEffectivePropsForPage(pageName) {
  const effectiveProps = getEffectivePropsForPage(pageName);
  useStore.setState({ [pageName]: effectiveProps });
}

useStore.setState(desktopModeProps);

export default useStore;
